@EventModular.Server.Modules.AffiliateMarketing.Api_HostAddress = http://localhost:5244

GET {{EventModular.Server.Modules.AffiliateMarketing.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
